version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pMRLJew8
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pMRLJew8
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
